name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Run library tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Enable Corepack
        # Required due to a limitation in setup-node https://github.com/actions/setup-node/issues/480#issuecomment-1820622085
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies with Yarn
        run: yarn install --immutable
      - name: Run tests
        run: yarn test
        env:
          NODE_ENV: production

  typecheck:
    name: Typecheck

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Enable Corepack
        # Required due to a limitation in setup-node https://github.com/actions/setup-node/issues/480#issuecomment-1820622085
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies with Yarn
        run: yarn install --immutable
      - name: Typecheck
        run: yarn run build
  style:
    name: Check style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Enable Corepack
        # Required due to a limitation in setup-node https://github.com/actions/setup-node/issues/480#issuecomment-1820622085
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies with Yarn
        run: yarn install --immutable
      - name: Check style with Prettier
        run: yarn run style
